name: My first workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello All"
      - name: Run multiple commands
        run: |
          echo "Hello from Actions"
          echo "Executed Job1 of the workflow"
